apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  namespace: yelb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
<<<<<<< HEAD
=======
      tier: cache
>>>>>>> 76923a7e11e5b796a3817592ab0caf6c87fe6a01
  template:
    metadata:
      labels:
        app: redis-server
        tier: cache
        secgroup: yelb-db
    spec:
      containers:
      - name: redis-server
<<<<<<< HEAD
        image: vdbharbor.vdoubleb.com/demo/redis:4.0.2
#        image: redis:4.0.2
=======
        image: redis:4.0.14
>>>>>>> 76923a7e11e5b796a3817592ab0caf6c87fe6a01
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-server
  labels:
    app: redis-server
    tier: cache
    secgroup: yelb-db
  namespace: yelb
spec:
  type: ClusterIP
  ports:
  - port: 6379
  selector:
    app: redis-server
    tier: cache
